# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backend/proto/signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backend/proto/signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62\x61\x63kend/proto/signal.proto\x12\x0c\x63rypto_surge\"\xfa\x03\n\rTradingSignal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x11\n\tsignal_id\x18\x03 \x01(\t\x12\x15\n\rcurrent_price\x18\x04 \x01(\x01\x12\x32\n\rprobabilities\x18\x05 \x01(\x0b\x32\x1b.crypto_surge.Probabilities\x12\x10\n\x08\x64\x65\x63ision\x18\x06 \x01(\t\x12\x0c\n\x04tier\x18\x07 \x01(\t\x12\x0f\n\x07utility\x18\x08 \x01(\x01\x12\x17\n\x0f\x65xpected_return\x18\t \x01(\x01\x12\x16\n\x0e\x65stimated_cost\x18\n \x01(\x01\x12\x15\n\rmodel_version\x18\x0b \x01(\t\x12\x17\n\x0f\x66\x65\x61ture_version\x18\x0c \x01(\t\x12\x16\n\x0esla_latency_ms\x18\r \x01(\x01\x12,\n\nthresholds\x18\x0e \x01(\x0b\x32\x18.crypto_surge.Thresholds\x12\x42\n\x0ctop_features\x18\x0f \x03(\x0b\x32,.crypto_surge.TradingSignal.TopFeaturesEntry\x12\x15\n\rquality_flags\x18\x10 \x03(\t\x1a\x32\n\x10TopFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x95\x01\n\rProbabilities\x12*\n\x07prob_5m\x18\x01 \x01(\x0b\x32\x19.crypto_surge.HorizonProb\x12+\n\x08prob_10m\x18\x02 \x01(\x0b\x32\x19.crypto_surge.HorizonProb\x12+\n\x08prob_30m\x18\x03 \x01(\x0b\x32\x19.crypto_surge.HorizonProb\"=\n\x0bHorizonProb\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0e\n\x06\x63i_low\x18\x02 \x01(\x01\x12\x0f\n\x07\x63i_high\x18\x03 \x01(\x01\"L\n\nThresholds\x12\x0b\n\x03tau\x18\x01 \x01(\x01\x12\r\n\x05kappa\x18\x02 \x01(\x01\x12\x10\n\x08theta_up\x18\x03 \x01(\x01\x12\x10\n\x08theta_dn\x18\x04 \x01(\x01\"\x80\x01\n\x0bSignalBatch\x12,\n\x07signals\x18\x01 \x03(\x0b\x32\x1b.crypto_surge.TradingSignal\x12\x1b\n\x13\x65xport_timestamp_ms\x18\x02 \x01(\x03\x12\x11\n\texport_id\x18\x03 \x01(\t\x12\x13\n\x0btotal_count\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend.proto.signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADINGSIGNAL_TOPFEATURESENTRY']._loaded_options = None
  _globals['_TRADINGSIGNAL_TOPFEATURESENTRY']._serialized_options = b'8\001'
  _globals['_TRADINGSIGNAL']._serialized_start=45
  _globals['_TRADINGSIGNAL']._serialized_end=551
  _globals['_TRADINGSIGNAL_TOPFEATURESENTRY']._serialized_start=501
  _globals['_TRADINGSIGNAL_TOPFEATURESENTRY']._serialized_end=551
  _globals['_PROBABILITIES']._serialized_start=554
  _globals['_PROBABILITIES']._serialized_end=703
  _globals['_HORIZONPROB']._serialized_start=705
  _globals['_HORIZONPROB']._serialized_end=766
  _globals['_THRESHOLDS']._serialized_start=768
  _globals['_THRESHOLDS']._serialized_end=844
  _globals['_SIGNALBATCH']._serialized_start=847
  _globals['_SIGNALBATCH']._serialized_end=975
# @@protoc_insertion_point(module_scope)
