[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "light"
primaryColor = "#007AFF"
backgroundColor = "#F2F2F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans-serif"

[browser]
gatherUsageStats = false
