[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "dark"
primaryColor = "#2962FF"
backgroundColor = "#131722"
secondaryBackgroundColor = "#1E222D"
textColor = "#D1D4DC"
font = "sans-serif"

[browser]
gatherUsageStats = false
